#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Otomasyon")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_CARIGRUPLARI(TBL_CARIGRUPLARI instance);
    partial void UpdateTBL_CARIGRUPLARI(TBL_CARIGRUPLARI instance);
    partial void DeleteTBL_CARIGRUPLARI(TBL_CARIGRUPLARI instance);
    partial void InsertTBL_CARILER(TBL_CARILER instance);
    partial void UpdateTBL_CARILER(TBL_CARILER instance);
    partial void DeleteTBL_CARILER(TBL_CARILER instance);
    partial void InsertTBL_STOKGRUPLARI(TBL_STOKGRUPLARI instance);
    partial void UpdateTBL_STOKGRUPLARI(TBL_STOKGRUPLARI instance);
    partial void DeleteTBL_STOKGRUPLARI(TBL_STOKGRUPLARI instance);
    partial void InsertTBL_STOKLAR(TBL_STOKLAR instance);
    partial void UpdateTBL_STOKLAR(TBL_STOKLAR instance);
    partial void DeleteTBL_STOKLAR(TBL_STOKLAR instance);
    partial void InsertTBL_CARIHAREKETLERI(TBL_CARIHAREKETLERI instance);
    partial void UpdateTBL_CARIHAREKETLERI(TBL_CARIHAREKETLERI instance);
    partial void DeleteTBL_CARIHAREKETLERI(TBL_CARIHAREKETLERI instance);
    partial void InsertTBL_KASAHAREKETLERI(TBL_KASAHAREKETLERI instance);
    partial void UpdateTBL_KASAHAREKETLERI(TBL_KASAHAREKETLERI instance);
    partial void DeleteTBL_KASAHAREKETLERI(TBL_KASAHAREKETLERI instance);
    partial void InsertTBL_KASALAR(TBL_KASALAR instance);
    partial void UpdateTBL_KASALAR(TBL_KASALAR instance);
    partial void DeleteTBL_KASALAR(TBL_KASALAR instance);
    partial void InsertTBL_BANKAHAREKETLERI(TBL_BANKAHAREKETLERI instance);
    partial void UpdateTBL_BANKAHAREKETLERI(TBL_BANKAHAREKETLERI instance);
    partial void DeleteTBL_BANKAHAREKETLERI(TBL_BANKAHAREKETLERI instance);
    partial void InsertTBL_BANKALAR(TBL_BANKALAR instance);
    partial void UpdateTBL_BANKALAR(TBL_BANKALAR instance);
    partial void DeleteTBL_BANKALAR(TBL_BANKALAR instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Otomasyon.Properties.Settings.Default.OtomasyonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_CARIGRUPLARI> TBL_CARIGRUPLARIs
		{
			get
			{
				return this.GetTable<TBL_CARIGRUPLARI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CARILER> TBL_CARILERs
		{
			get
			{
				return this.GetTable<TBL_CARILER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_STOKGRUPLARI> TBL_STOKGRUPLARIs
		{
			get
			{
				return this.GetTable<TBL_STOKGRUPLARI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_STOKLAR> TBL_STOKLARs
		{
			get
			{
				return this.GetTable<TBL_STOKLAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CARIHAREKETLERI> TBL_CARIHAREKETLERIs
		{
			get
			{
				return this.GetTable<TBL_CARIHAREKETLERI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_KASAHAREKETLERI> TBL_KASAHAREKETLERIs
		{
			get
			{
				return this.GetTable<TBL_KASAHAREKETLERI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_KASALAR> TBL_KASALARs
		{
			get
			{
				return this.GetTable<TBL_KASALAR>();
			}
		}
		
		public System.Data.Linq.Table<VW_KASADURUM> VW_KASADURUMs
		{
			get
			{
				return this.GetTable<VW_KASADURUM>();
			}
		}
		
		public System.Data.Linq.Table<VW_KASAHAREKETLERI> VW_KASAHAREKETLERIs
		{
			get
			{
				return this.GetTable<VW_KASAHAREKETLERI>();
			}
		}
		
		public System.Data.Linq.Table<VW_KASALISTESI> VW_KASALISTESIs
		{
			get
			{
				return this.GetTable<VW_KASALISTESI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_BANKAHAREKETLERI> TBL_BANKAHAREKETLERIs
		{
			get
			{
				return this.GetTable<TBL_BANKAHAREKETLERI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_BANKALAR> TBL_BANKALARs
		{
			get
			{
				return this.GetTable<TBL_BANKALAR>();
			}
		}
		
		public System.Data.Linq.Table<VW_BANKADURUM> VW_BANKADURUMs
		{
			get
			{
				return this.GetTable<VW_BANKADURUM>();
			}
		}
		
		public System.Data.Linq.Table<VW_BANKAHAREKETLERI> VW_BANKAHAREKETLERIs
		{
			get
			{
				return this.GetTable<VW_BANKAHAREKETLERI>();
			}
		}
		
		public System.Data.Linq.Table<VW_BANKALISTESI> VW_BANKALISTESIs
		{
			get
			{
				return this.GetTable<VW_BANKALISTESI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CARIGRUPLARI")]
	public partial class TBL_CARIGRUPLARI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GRUPADI;
		
		private string _GRUPKODU;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDITDATE;
		
		private System.Nullable<int> _EDITUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGRUPADIChanging(string value);
    partial void OnGRUPADIChanged();
    partial void OnGRUPKODUChanging(string value);
    partial void OnGRUPKODUChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDITDATEChanged();
    partial void OnEDITUSERChanging(System.Nullable<int> value);
    partial void OnEDITUSERChanged();
    #endregion
		
		public TBL_CARIGRUPLARI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPADI", DbType="NVarChar(30)")]
		public string GRUPADI
		{
			get
			{
				return this._GRUPADI;
			}
			set
			{
				if ((this._GRUPADI != value))
				{
					this.OnGRUPADIChanging(value);
					this.SendPropertyChanging();
					this._GRUPADI = value;
					this.SendPropertyChanged("GRUPADI");
					this.OnGRUPADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPKODU", DbType="NVarChar(30)")]
		public string GRUPKODU
		{
			get
			{
				return this._GRUPKODU;
			}
			set
			{
				if ((this._GRUPKODU != value))
				{
					this.OnGRUPKODUChanging(value);
					this.SendPropertyChanging();
					this._GRUPKODU = value;
					this.SendPropertyChanged("GRUPKODU");
					this.OnGRUPKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDITDATE
		{
			get
			{
				return this._EDITDATE;
			}
			set
			{
				if ((this._EDITDATE != value))
				{
					this.OnEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._EDITDATE = value;
					this.SendPropertyChanged("EDITDATE");
					this.OnEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITUSER", DbType="Int")]
		public System.Nullable<int> EDITUSER
		{
			get
			{
				return this._EDITUSER;
			}
			set
			{
				if ((this._EDITUSER != value))
				{
					this.OnEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._EDITUSER = value;
					this.SendPropertyChanged("EDITUSER");
					this.OnEDITUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CARILER")]
	public partial class TBL_CARILER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CARIKODU;
		
		private string _CARIADI;
		
		private string _VERGIDAIRESI;
		
		private string _VERGINO;
		
		private System.Nullable<int> _GRUPID;
		
		private string _ULKE;
		
		private string _SEHIR;
		
		private string _ILCE;
		
		private string _ADRES;
		
		private string _TELEFON1;
		
		private string _TELEFON2;
		
		private string _FAX1;
		
		private string _FAX2;
		
		private string _WEBADRES;
		
		private string _MAILINFO;
		
		private string _YETKILI1;
		
		private string _YETKILIMAIL1;
		
		private string _YETKILI2;
		
		private string _YETKILIMAIL2;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDITDATE;
		
		private System.Nullable<int> _EDITUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCARIKODUChanging(string value);
    partial void OnCARIKODUChanged();
    partial void OnCARIADIChanging(string value);
    partial void OnCARIADIChanged();
    partial void OnVERGIDAIRESIChanging(string value);
    partial void OnVERGIDAIRESIChanged();
    partial void OnVERGINOChanging(string value);
    partial void OnVERGINOChanged();
    partial void OnGRUPIDChanging(System.Nullable<int> value);
    partial void OnGRUPIDChanged();
    partial void OnULKEChanging(string value);
    partial void OnULKEChanged();
    partial void OnSEHIRChanging(string value);
    partial void OnSEHIRChanged();
    partial void OnILCEChanging(string value);
    partial void OnILCEChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    partial void OnTELEFON1Changing(string value);
    partial void OnTELEFON1Changed();
    partial void OnTELEFON2Changing(string value);
    partial void OnTELEFON2Changed();
    partial void OnFAX1Changing(string value);
    partial void OnFAX1Changed();
    partial void OnFAX2Changing(string value);
    partial void OnFAX2Changed();
    partial void OnWEBADRESChanging(string value);
    partial void OnWEBADRESChanged();
    partial void OnMAILINFOChanging(string value);
    partial void OnMAILINFOChanged();
    partial void OnYETKILI1Changing(string value);
    partial void OnYETKILI1Changed();
    partial void OnYETKILIMAIL1Changing(string value);
    partial void OnYETKILIMAIL1Changed();
    partial void OnYETKILI2Changing(string value);
    partial void OnYETKILI2Changed();
    partial void OnYETKILIMAIL2Changing(string value);
    partial void OnYETKILIMAIL2Changed();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDITDATEChanged();
    partial void OnEDITUSERChanging(System.Nullable<int> value);
    partial void OnEDITUSERChanged();
    #endregion
		
		public TBL_CARILER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIKODU", DbType="NVarChar(30)")]
		public string CARIKODU
		{
			get
			{
				return this._CARIKODU;
			}
			set
			{
				if ((this._CARIKODU != value))
				{
					this.OnCARIKODUChanging(value);
					this.SendPropertyChanging();
					this._CARIKODU = value;
					this.SendPropertyChanged("CARIKODU");
					this.OnCARIKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIADI", DbType="NVarChar(30)")]
		public string CARIADI
		{
			get
			{
				return this._CARIADI;
			}
			set
			{
				if ((this._CARIADI != value))
				{
					this.OnCARIADIChanging(value);
					this.SendPropertyChanging();
					this._CARIADI = value;
					this.SendPropertyChanged("CARIADI");
					this.OnCARIADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGIDAIRESI", DbType="NVarChar(50)")]
		public string VERGIDAIRESI
		{
			get
			{
				return this._VERGIDAIRESI;
			}
			set
			{
				if ((this._VERGIDAIRESI != value))
				{
					this.OnVERGIDAIRESIChanging(value);
					this.SendPropertyChanging();
					this._VERGIDAIRESI = value;
					this.SendPropertyChanged("VERGIDAIRESI");
					this.OnVERGIDAIRESIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGINO", DbType="NVarChar(20)")]
		public string VERGINO
		{
			get
			{
				return this._VERGINO;
			}
			set
			{
				if ((this._VERGINO != value))
				{
					this.OnVERGINOChanging(value);
					this.SendPropertyChanging();
					this._VERGINO = value;
					this.SendPropertyChanged("VERGINO");
					this.OnVERGINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPID", DbType="Int")]
		public System.Nullable<int> GRUPID
		{
			get
			{
				return this._GRUPID;
			}
			set
			{
				if ((this._GRUPID != value))
				{
					this.OnGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._GRUPID = value;
					this.SendPropertyChanged("GRUPID");
					this.OnGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ULKE", DbType="NVarChar(30)")]
		public string ULKE
		{
			get
			{
				return this._ULKE;
			}
			set
			{
				if ((this._ULKE != value))
				{
					this.OnULKEChanging(value);
					this.SendPropertyChanging();
					this._ULKE = value;
					this.SendPropertyChanged("ULKE");
					this.OnULKEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEHIR", DbType="NVarChar(30)")]
		public string SEHIR
		{
			get
			{
				return this._SEHIR;
			}
			set
			{
				if ((this._SEHIR != value))
				{
					this.OnSEHIRChanging(value);
					this.SendPropertyChanging();
					this._SEHIR = value;
					this.SendPropertyChanged("SEHIR");
					this.OnSEHIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ILCE", DbType="NVarChar(30)")]
		public string ILCE
		{
			get
			{
				return this._ILCE;
			}
			set
			{
				if ((this._ILCE != value))
				{
					this.OnILCEChanging(value);
					this.SendPropertyChanging();
					this._ILCE = value;
					this.SendPropertyChanged("ILCE");
					this.OnILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON1", DbType="NVarChar(16)")]
		public string TELEFON1
		{
			get
			{
				return this._TELEFON1;
			}
			set
			{
				if ((this._TELEFON1 != value))
				{
					this.OnTELEFON1Changing(value);
					this.SendPropertyChanging();
					this._TELEFON1 = value;
					this.SendPropertyChanged("TELEFON1");
					this.OnTELEFON1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON2", DbType="NVarChar(16)")]
		public string TELEFON2
		{
			get
			{
				return this._TELEFON2;
			}
			set
			{
				if ((this._TELEFON2 != value))
				{
					this.OnTELEFON2Changing(value);
					this.SendPropertyChanging();
					this._TELEFON2 = value;
					this.SendPropertyChanged("TELEFON2");
					this.OnTELEFON2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX1", DbType="NVarChar(16)")]
		public string FAX1
		{
			get
			{
				return this._FAX1;
			}
			set
			{
				if ((this._FAX1 != value))
				{
					this.OnFAX1Changing(value);
					this.SendPropertyChanging();
					this._FAX1 = value;
					this.SendPropertyChanged("FAX1");
					this.OnFAX1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX2", DbType="NVarChar(16)")]
		public string FAX2
		{
			get
			{
				return this._FAX2;
			}
			set
			{
				if ((this._FAX2 != value))
				{
					this.OnFAX2Changing(value);
					this.SendPropertyChanging();
					this._FAX2 = value;
					this.SendPropertyChanged("FAX2");
					this.OnFAX2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEBADRES", DbType="NVarChar(150)")]
		public string WEBADRES
		{
			get
			{
				return this._WEBADRES;
			}
			set
			{
				if ((this._WEBADRES != value))
				{
					this.OnWEBADRESChanging(value);
					this.SendPropertyChanging();
					this._WEBADRES = value;
					this.SendPropertyChanged("WEBADRES");
					this.OnWEBADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAILINFO", DbType="NVarChar(250)")]
		public string MAILINFO
		{
			get
			{
				return this._MAILINFO;
			}
			set
			{
				if ((this._MAILINFO != value))
				{
					this.OnMAILINFOChanging(value);
					this.SendPropertyChanging();
					this._MAILINFO = value;
					this.SendPropertyChanged("MAILINFO");
					this.OnMAILINFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILI1", DbType="NVarChar(50)")]
		public string YETKILI1
		{
			get
			{
				return this._YETKILI1;
			}
			set
			{
				if ((this._YETKILI1 != value))
				{
					this.OnYETKILI1Changing(value);
					this.SendPropertyChanging();
					this._YETKILI1 = value;
					this.SendPropertyChanged("YETKILI1");
					this.OnYETKILI1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILIMAIL1", DbType="NVarChar(250)")]
		public string YETKILIMAIL1
		{
			get
			{
				return this._YETKILIMAIL1;
			}
			set
			{
				if ((this._YETKILIMAIL1 != value))
				{
					this.OnYETKILIMAIL1Changing(value);
					this.SendPropertyChanging();
					this._YETKILIMAIL1 = value;
					this.SendPropertyChanged("YETKILIMAIL1");
					this.OnYETKILIMAIL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILI2", DbType="NVarChar(50)")]
		public string YETKILI2
		{
			get
			{
				return this._YETKILI2;
			}
			set
			{
				if ((this._YETKILI2 != value))
				{
					this.OnYETKILI2Changing(value);
					this.SendPropertyChanging();
					this._YETKILI2 = value;
					this.SendPropertyChanged("YETKILI2");
					this.OnYETKILI2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILIMAIL2", DbType="NVarChar(250)")]
		public string YETKILIMAIL2
		{
			get
			{
				return this._YETKILIMAIL2;
			}
			set
			{
				if ((this._YETKILIMAIL2 != value))
				{
					this.OnYETKILIMAIL2Changing(value);
					this.SendPropertyChanging();
					this._YETKILIMAIL2 = value;
					this.SendPropertyChanged("YETKILIMAIL2");
					this.OnYETKILIMAIL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDITDATE
		{
			get
			{
				return this._EDITDATE;
			}
			set
			{
				if ((this._EDITDATE != value))
				{
					this.OnEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._EDITDATE = value;
					this.SendPropertyChanged("EDITDATE");
					this.OnEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITUSER", DbType="Int")]
		public System.Nullable<int> EDITUSER
		{
			get
			{
				return this._EDITUSER;
			}
			set
			{
				if ((this._EDITUSER != value))
				{
					this.OnEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._EDITUSER = value;
					this.SendPropertyChanged("EDITUSER");
					this.OnEDITUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_STOKGRUPLARI")]
	public partial class TBL_STOKGRUPLARI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GRUPADI;
		
		private string _GRUPKODU;
		
		private System.Nullable<int> _GRUPSAVEUSER;
		
		private System.Nullable<System.DateTime> _GRUPSAVEDATE;
		
		private System.Nullable<int> _GRUPEDITUSER;
		
		private System.Nullable<System.DateTime> _GRUPEDITDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGRUPADIChanging(string value);
    partial void OnGRUPADIChanged();
    partial void OnGRUPKODUChanging(string value);
    partial void OnGRUPKODUChanged();
    partial void OnGRUPSAVEUSERChanging(System.Nullable<int> value);
    partial void OnGRUPSAVEUSERChanged();
    partial void OnGRUPSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGRUPSAVEDATEChanged();
    partial void OnGRUPEDITUSERChanging(System.Nullable<int> value);
    partial void OnGRUPEDITUSERChanged();
    partial void OnGRUPEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGRUPEDITDATEChanged();
    #endregion
		
		public TBL_STOKGRUPLARI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPADI", DbType="NVarChar(30)")]
		public string GRUPADI
		{
			get
			{
				return this._GRUPADI;
			}
			set
			{
				if ((this._GRUPADI != value))
				{
					this.OnGRUPADIChanging(value);
					this.SendPropertyChanging();
					this._GRUPADI = value;
					this.SendPropertyChanged("GRUPADI");
					this.OnGRUPADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPKODU", DbType="NVarChar(30)")]
		public string GRUPKODU
		{
			get
			{
				return this._GRUPKODU;
			}
			set
			{
				if ((this._GRUPKODU != value))
				{
					this.OnGRUPKODUChanging(value);
					this.SendPropertyChanging();
					this._GRUPKODU = value;
					this.SendPropertyChanged("GRUPKODU");
					this.OnGRUPKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPSAVEUSER", DbType="Int")]
		public System.Nullable<int> GRUPSAVEUSER
		{
			get
			{
				return this._GRUPSAVEUSER;
			}
			set
			{
				if ((this._GRUPSAVEUSER != value))
				{
					this.OnGRUPSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._GRUPSAVEUSER = value;
					this.SendPropertyChanged("GRUPSAVEUSER");
					this.OnGRUPSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GRUPSAVEDATE
		{
			get
			{
				return this._GRUPSAVEDATE;
			}
			set
			{
				if ((this._GRUPSAVEDATE != value))
				{
					this.OnGRUPSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._GRUPSAVEDATE = value;
					this.SendPropertyChanged("GRUPSAVEDATE");
					this.OnGRUPSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPEDITUSER", DbType="Int")]
		public System.Nullable<int> GRUPEDITUSER
		{
			get
			{
				return this._GRUPEDITUSER;
			}
			set
			{
				if ((this._GRUPEDITUSER != value))
				{
					this.OnGRUPEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._GRUPEDITUSER = value;
					this.SendPropertyChanged("GRUPEDITUSER");
					this.OnGRUPEDITUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GRUPEDITDATE
		{
			get
			{
				return this._GRUPEDITDATE;
			}
			set
			{
				if ((this._GRUPEDITDATE != value))
				{
					this.OnGRUPEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._GRUPEDITDATE = value;
					this.SendPropertyChanged("GRUPEDITDATE");
					this.OnGRUPEDITDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_STOKLAR")]
	public partial class TBL_STOKLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _STOKBARKOD;
		
		private string _STOKKODU;
		
		private string _STOKADI;
		
		private string _STOKBIRIM;
		
		private System.Nullable<decimal> _STOKALISFIYAT;
		
		private System.Nullable<decimal> _STOKSATISFIYAT;
		
		private System.Nullable<decimal> _STOKALISKDV;
		
		private System.Nullable<decimal> _STOKSATISKDV;
		
		private System.Nullable<int> _STOKGRUPID;
		
		private System.Data.Linq.Binary _STOKRESIM;
		
		private System.Nullable<int> _STOKSAVEUSER;
		
		private System.Nullable<System.DateTime> _STOKSAVEDATE;
		
		private System.Nullable<int> _STOKEDITUSER;
		
		private System.Nullable<System.DateTime> _STOKEDITDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSTOKBARKODChanging(string value);
    partial void OnSTOKBARKODChanged();
    partial void OnSTOKKODUChanging(string value);
    partial void OnSTOKKODUChanged();
    partial void OnSTOKADIChanging(string value);
    partial void OnSTOKADIChanged();
    partial void OnSTOKBIRIMChanging(string value);
    partial void OnSTOKBIRIMChanged();
    partial void OnSTOKALISFIYATChanging(System.Nullable<decimal> value);
    partial void OnSTOKALISFIYATChanged();
    partial void OnSTOKSATISFIYATChanging(System.Nullable<decimal> value);
    partial void OnSTOKSATISFIYATChanged();
    partial void OnSTOKALISKDVChanging(System.Nullable<decimal> value);
    partial void OnSTOKALISKDVChanged();
    partial void OnSTOKSATISKDVChanging(System.Nullable<decimal> value);
    partial void OnSTOKSATISKDVChanged();
    partial void OnSTOKGRUPIDChanging(System.Nullable<int> value);
    partial void OnSTOKGRUPIDChanged();
    partial void OnSTOKRESIMChanging(System.Data.Linq.Binary value);
    partial void OnSTOKRESIMChanged();
    partial void OnSTOKSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSTOKSAVEUSERChanged();
    partial void OnSTOKSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTOKSAVEDATEChanged();
    partial void OnSTOKEDITUSERChanging(System.Nullable<int> value);
    partial void OnSTOKEDITUSERChanged();
    partial void OnSTOKEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTOKEDITDATEChanged();
    #endregion
		
		public TBL_STOKLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKBARKOD", DbType="NVarChar(30)")]
		public string STOKBARKOD
		{
			get
			{
				return this._STOKBARKOD;
			}
			set
			{
				if ((this._STOKBARKOD != value))
				{
					this.OnSTOKBARKODChanging(value);
					this.SendPropertyChanging();
					this._STOKBARKOD = value;
					this.SendPropertyChanged("STOKBARKOD");
					this.OnSTOKBARKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKKODU", DbType="NVarChar(20)")]
		public string STOKKODU
		{
			get
			{
				return this._STOKKODU;
			}
			set
			{
				if ((this._STOKKODU != value))
				{
					this.OnSTOKKODUChanging(value);
					this.SendPropertyChanging();
					this._STOKKODU = value;
					this.SendPropertyChanged("STOKKODU");
					this.OnSTOKKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKADI", DbType="NVarChar(50)")]
		public string STOKADI
		{
			get
			{
				return this._STOKADI;
			}
			set
			{
				if ((this._STOKADI != value))
				{
					this.OnSTOKADIChanging(value);
					this.SendPropertyChanging();
					this._STOKADI = value;
					this.SendPropertyChanged("STOKADI");
					this.OnSTOKADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKBIRIM", DbType="NVarChar(15)")]
		public string STOKBIRIM
		{
			get
			{
				return this._STOKBIRIM;
			}
			set
			{
				if ((this._STOKBIRIM != value))
				{
					this.OnSTOKBIRIMChanging(value);
					this.SendPropertyChanging();
					this._STOKBIRIM = value;
					this.SendPropertyChanged("STOKBIRIM");
					this.OnSTOKBIRIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKALISFIYAT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKALISFIYAT
		{
			get
			{
				return this._STOKALISFIYAT;
			}
			set
			{
				if ((this._STOKALISFIYAT != value))
				{
					this.OnSTOKALISFIYATChanging(value);
					this.SendPropertyChanging();
					this._STOKALISFIYAT = value;
					this.SendPropertyChanged("STOKALISFIYAT");
					this.OnSTOKALISFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSATISFIYAT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKSATISFIYAT
		{
			get
			{
				return this._STOKSATISFIYAT;
			}
			set
			{
				if ((this._STOKSATISFIYAT != value))
				{
					this.OnSTOKSATISFIYATChanging(value);
					this.SendPropertyChanging();
					this._STOKSATISFIYAT = value;
					this.SendPropertyChanged("STOKSATISFIYAT");
					this.OnSTOKSATISFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKALISKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKALISKDV
		{
			get
			{
				return this._STOKALISKDV;
			}
			set
			{
				if ((this._STOKALISKDV != value))
				{
					this.OnSTOKALISKDVChanging(value);
					this.SendPropertyChanging();
					this._STOKALISKDV = value;
					this.SendPropertyChanged("STOKALISKDV");
					this.OnSTOKALISKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSATISKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKSATISKDV
		{
			get
			{
				return this._STOKSATISKDV;
			}
			set
			{
				if ((this._STOKSATISKDV != value))
				{
					this.OnSTOKSATISKDVChanging(value);
					this.SendPropertyChanging();
					this._STOKSATISKDV = value;
					this.SendPropertyChanged("STOKSATISKDV");
					this.OnSTOKSATISKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKGRUPID", DbType="Int")]
		public System.Nullable<int> STOKGRUPID
		{
			get
			{
				return this._STOKGRUPID;
			}
			set
			{
				if ((this._STOKGRUPID != value))
				{
					this.OnSTOKGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._STOKGRUPID = value;
					this.SendPropertyChanged("STOKGRUPID");
					this.OnSTOKGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKRESIM", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary STOKRESIM
		{
			get
			{
				return this._STOKRESIM;
			}
			set
			{
				if ((this._STOKRESIM != value))
				{
					this.OnSTOKRESIMChanging(value);
					this.SendPropertyChanging();
					this._STOKRESIM = value;
					this.SendPropertyChanged("STOKRESIM");
					this.OnSTOKRESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSAVEUSER", DbType="Int")]
		public System.Nullable<int> STOKSAVEUSER
		{
			get
			{
				return this._STOKSAVEUSER;
			}
			set
			{
				if ((this._STOKSAVEUSER != value))
				{
					this.OnSTOKSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._STOKSAVEUSER = value;
					this.SendPropertyChanged("STOKSAVEUSER");
					this.OnSTOKSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOKSAVEDATE
		{
			get
			{
				return this._STOKSAVEDATE;
			}
			set
			{
				if ((this._STOKSAVEDATE != value))
				{
					this.OnSTOKSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._STOKSAVEDATE = value;
					this.SendPropertyChanged("STOKSAVEDATE");
					this.OnSTOKSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKEDITUSER", DbType="Int")]
		public System.Nullable<int> STOKEDITUSER
		{
			get
			{
				return this._STOKEDITUSER;
			}
			set
			{
				if ((this._STOKEDITUSER != value))
				{
					this.OnSTOKEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._STOKEDITUSER = value;
					this.SendPropertyChanged("STOKEDITUSER");
					this.OnSTOKEDITUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKEDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOKEDITDATE
		{
			get
			{
				return this._STOKEDITDATE;
			}
			set
			{
				if ((this._STOKEDITDATE != value))
				{
					this.OnSTOKEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._STOKEDITDATE = value;
					this.SendPropertyChanged("STOKEDITDATE");
					this.OnSTOKEDITDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CARIHAREKETLERI")]
	public partial class TBL_CARIHAREKETLERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _CARIID;
		
		private string _EVRAKTURU;
		
		private System.Nullable<int> _EVRAKID;
		
		private System.Nullable<decimal> _BORC;
		
		private System.Nullable<decimal> _ALACAK;
		
		private string _ACIKLAMA;
		
		private System.Nullable<System.DateTime> _TARIH;
		
		private string _TIPI;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDITDATE;
		
		private System.Nullable<int> _EDITUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCARIIDChanging(System.Nullable<int> value);
    partial void OnCARIIDChanged();
    partial void OnEVRAKTURUChanging(string value);
    partial void OnEVRAKTURUChanged();
    partial void OnEVRAKIDChanging(System.Nullable<int> value);
    partial void OnEVRAKIDChanged();
    partial void OnBORCChanging(System.Nullable<decimal> value);
    partial void OnBORCChanged();
    partial void OnALACAKChanging(System.Nullable<decimal> value);
    partial void OnALACAKChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    partial void OnTIPIChanging(string value);
    partial void OnTIPIChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDITDATEChanged();
    partial void OnEDITUSERChanging(System.Nullable<int> value);
    partial void OnEDITUSERChanged();
    #endregion
		
		public TBL_CARIHAREKETLERI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIID", DbType="Int")]
		public System.Nullable<int> CARIID
		{
			get
			{
				return this._CARIID;
			}
			set
			{
				if ((this._CARIID != value))
				{
					this.OnCARIIDChanging(value);
					this.SendPropertyChanging();
					this._CARIID = value;
					this.SendPropertyChanged("CARIID");
					this.OnCARIIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKTURU", DbType="NVarChar(30)")]
		public string EVRAKTURU
		{
			get
			{
				return this._EVRAKTURU;
			}
			set
			{
				if ((this._EVRAKTURU != value))
				{
					this.OnEVRAKTURUChanging(value);
					this.SendPropertyChanging();
					this._EVRAKTURU = value;
					this.SendPropertyChanged("EVRAKTURU");
					this.OnEVRAKTURUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKID", DbType="Int")]
		public System.Nullable<int> EVRAKID
		{
			get
			{
				return this._EVRAKID;
			}
			set
			{
				if ((this._EVRAKID != value))
				{
					this.OnEVRAKIDChanging(value);
					this.SendPropertyChanging();
					this._EVRAKID = value;
					this.SendPropertyChanged("EVRAKID");
					this.OnEVRAKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORC", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> BORC
		{
			get
			{
				return this._BORC;
			}
			set
			{
				if ((this._BORC != value))
				{
					this.OnBORCChanging(value);
					this.SendPropertyChanging();
					this._BORC = value;
					this.SendPropertyChanged("BORC");
					this.OnBORCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALACAK", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ALACAK
		{
			get
			{
				return this._ALACAK;
			}
			set
			{
				if ((this._ALACAK != value))
				{
					this.OnALACAKChanging(value);
					this.SendPropertyChanging();
					this._ALACAK = value;
					this.SendPropertyChanged("ALACAK");
					this.OnALACAKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPI", DbType="NVarChar(25)")]
		public string TIPI
		{
			get
			{
				return this._TIPI;
			}
			set
			{
				if ((this._TIPI != value))
				{
					this.OnTIPIChanging(value);
					this.SendPropertyChanging();
					this._TIPI = value;
					this.SendPropertyChanged("TIPI");
					this.OnTIPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDITDATE
		{
			get
			{
				return this._EDITDATE;
			}
			set
			{
				if ((this._EDITDATE != value))
				{
					this.OnEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._EDITDATE = value;
					this.SendPropertyChanged("EDITDATE");
					this.OnEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITUSER", DbType="Int")]
		public System.Nullable<int> EDITUSER
		{
			get
			{
				return this._EDITUSER;
			}
			set
			{
				if ((this._EDITUSER != value))
				{
					this.OnEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._EDITUSER = value;
					this.SendPropertyChanged("EDITUSER");
					this.OnEDITUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_KASAHAREKETLERI")]
	public partial class TBL_KASAHAREKETLERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _KASAID;
		
		private System.Nullable<int> _CARIID;
		
		private string _BELGENO;
		
		private System.Nullable<System.DateTime> _TARIH;
		
		private string _EVRAKTURU;
		
		private System.Nullable<int> _EVRAKID;
		
		private string _GCKODU;
		
		private System.Nullable<decimal> _TUTAR;
		
		private string _ACIKLAMA;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDITDATE;
		
		private System.Nullable<int> _EDITUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKASAIDChanging(System.Nullable<int> value);
    partial void OnKASAIDChanged();
    partial void OnCARIIDChanging(System.Nullable<int> value);
    partial void OnCARIIDChanged();
    partial void OnBELGENOChanging(string value);
    partial void OnBELGENOChanged();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    partial void OnEVRAKTURUChanging(string value);
    partial void OnEVRAKTURUChanged();
    partial void OnEVRAKIDChanging(System.Nullable<int> value);
    partial void OnEVRAKIDChanged();
    partial void OnGCKODUChanging(string value);
    partial void OnGCKODUChanged();
    partial void OnTUTARChanging(System.Nullable<decimal> value);
    partial void OnTUTARChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDITDATEChanged();
    partial void OnEDITUSERChanging(System.Nullable<int> value);
    partial void OnEDITUSERChanged();
    #endregion
		
		public TBL_KASAHAREKETLERI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAID", DbType="Int")]
		public System.Nullable<int> KASAID
		{
			get
			{
				return this._KASAID;
			}
			set
			{
				if ((this._KASAID != value))
				{
					this.OnKASAIDChanging(value);
					this.SendPropertyChanging();
					this._KASAID = value;
					this.SendPropertyChanged("KASAID");
					this.OnKASAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIID", DbType="Int")]
		public System.Nullable<int> CARIID
		{
			get
			{
				return this._CARIID;
			}
			set
			{
				if ((this._CARIID != value))
				{
					this.OnCARIIDChanging(value);
					this.SendPropertyChanging();
					this._CARIID = value;
					this.SendPropertyChanged("CARIID");
					this.OnCARIIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGENO", DbType="NVarChar(50)")]
		public string BELGENO
		{
			get
			{
				return this._BELGENO;
			}
			set
			{
				if ((this._BELGENO != value))
				{
					this.OnBELGENOChanging(value);
					this.SendPropertyChanging();
					this._BELGENO = value;
					this.SendPropertyChanged("BELGENO");
					this.OnBELGENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKTURU", DbType="NVarChar(30)")]
		public string EVRAKTURU
		{
			get
			{
				return this._EVRAKTURU;
			}
			set
			{
				if ((this._EVRAKTURU != value))
				{
					this.OnEVRAKTURUChanging(value);
					this.SendPropertyChanging();
					this._EVRAKTURU = value;
					this.SendPropertyChanged("EVRAKTURU");
					this.OnEVRAKTURUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKID", DbType="Int")]
		public System.Nullable<int> EVRAKID
		{
			get
			{
				return this._EVRAKID;
			}
			set
			{
				if ((this._EVRAKID != value))
				{
					this.OnEVRAKIDChanging(value);
					this.SendPropertyChanging();
					this._EVRAKID = value;
					this.SendPropertyChanged("EVRAKID");
					this.OnEVRAKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCKODU", DbType="NVarChar(1)")]
		public string GCKODU
		{
			get
			{
				return this._GCKODU;
			}
			set
			{
				if ((this._GCKODU != value))
				{
					this.OnGCKODUChanging(value);
					this.SendPropertyChanging();
					this._GCKODU = value;
					this.SendPropertyChanged("GCKODU");
					this.OnGCKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUTAR", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TUTAR
		{
			get
			{
				return this._TUTAR;
			}
			set
			{
				if ((this._TUTAR != value))
				{
					this.OnTUTARChanging(value);
					this.SendPropertyChanging();
					this._TUTAR = value;
					this.SendPropertyChanged("TUTAR");
					this.OnTUTARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDITDATE
		{
			get
			{
				return this._EDITDATE;
			}
			set
			{
				if ((this._EDITDATE != value))
				{
					this.OnEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._EDITDATE = value;
					this.SendPropertyChanged("EDITDATE");
					this.OnEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITUSER", DbType="Int")]
		public System.Nullable<int> EDITUSER
		{
			get
			{
				return this._EDITUSER;
			}
			set
			{
				if ((this._EDITUSER != value))
				{
					this.OnEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._EDITUSER = value;
					this.SendPropertyChanged("EDITUSER");
					this.OnEDITUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_KASALAR")]
	public partial class TBL_KASALAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KASAKODU;
		
		private string _KASAADI;
		
		private string _ACIKLAMA;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDITDATE;
		
		private System.Nullable<int> _EDITUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKASAKODUChanging(string value);
    partial void OnKASAKODUChanged();
    partial void OnKASAADIChanging(string value);
    partial void OnKASAADIChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDITDATEChanged();
    partial void OnEDITUSERChanging(System.Nullable<int> value);
    partial void OnEDITUSERChanged();
    #endregion
		
		public TBL_KASALAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAKODU", DbType="NVarChar(30)")]
		public string KASAKODU
		{
			get
			{
				return this._KASAKODU;
			}
			set
			{
				if ((this._KASAKODU != value))
				{
					this.OnKASAKODUChanging(value);
					this.SendPropertyChanging();
					this._KASAKODU = value;
					this.SendPropertyChanged("KASAKODU");
					this.OnKASAKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAADI", DbType="NVarChar(30)")]
		public string KASAADI
		{
			get
			{
				return this._KASAADI;
			}
			set
			{
				if ((this._KASAADI != value))
				{
					this.OnKASAADIChanging(value);
					this.SendPropertyChanging();
					this._KASAADI = value;
					this.SendPropertyChanged("KASAADI");
					this.OnKASAADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDITDATE
		{
			get
			{
				return this._EDITDATE;
			}
			set
			{
				if ((this._EDITDATE != value))
				{
					this.OnEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._EDITDATE = value;
					this.SendPropertyChanged("EDITDATE");
					this.OnEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITUSER", DbType="Int")]
		public System.Nullable<int> EDITUSER
		{
			get
			{
				return this._EDITUSER;
			}
			set
			{
				if ((this._EDITUSER != value))
				{
					this.OnEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._EDITUSER = value;
					this.SendPropertyChanged("EDITUSER");
					this.OnEDITUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KASADURUM")]
	public partial class VW_KASADURUM
	{
		
		private System.Nullable<int> _KASAID;
		
		private System.Nullable<decimal> _GIRIS;
		
		private System.Nullable<decimal> _CIKIS;
		
		private System.Nullable<decimal> _BAKIYE;
		
		public VW_KASADURUM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAID", DbType="Int")]
		public System.Nullable<int> KASAID
		{
			get
			{
				return this._KASAID;
			}
			set
			{
				if ((this._KASAID != value))
				{
					this._KASAID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIRIS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> GIRIS
		{
			get
			{
				return this._GIRIS;
			}
			set
			{
				if ((this._GIRIS != value))
				{
					this._GIRIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIKIS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CIKIS
		{
			get
			{
				return this._CIKIS;
			}
			set
			{
				if ((this._CIKIS != value))
				{
					this._CIKIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAKIYE", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> BAKIYE
		{
			get
			{
				return this._BAKIYE;
			}
			set
			{
				if ((this._BAKIYE != value))
				{
					this._BAKIYE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KASAHAREKETLERI")]
	public partial class VW_KASAHAREKETLERI
	{
		
		private System.Nullable<int> _KASAID;
		
		private System.Nullable<int> _CARIID;
		
		private int _ID;
		
		private string _KASAKODU;
		
		private string _KASAADI;
		
		private string _CARIKODU;
		
		private string _CARIADI;
		
		private string _BELGENO;
		
		private System.Nullable<System.DateTime> _TARIH;
		
		private string _EVRAKTURU;
		
		private System.Nullable<int> _EVRAKID;
		
		private System.Nullable<decimal> _GIRIS;
		
		private System.Nullable<decimal> _CIKIS;
		
		private string _ACIKLAMA;
		
		public VW_KASAHAREKETLERI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAID", DbType="Int")]
		public System.Nullable<int> KASAID
		{
			get
			{
				return this._KASAID;
			}
			set
			{
				if ((this._KASAID != value))
				{
					this._KASAID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIID", DbType="Int")]
		public System.Nullable<int> CARIID
		{
			get
			{
				return this._CARIID;
			}
			set
			{
				if ((this._CARIID != value))
				{
					this._CARIID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAKODU", DbType="NVarChar(30)")]
		public string KASAKODU
		{
			get
			{
				return this._KASAKODU;
			}
			set
			{
				if ((this._KASAKODU != value))
				{
					this._KASAKODU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAADI", DbType="NVarChar(30)")]
		public string KASAADI
		{
			get
			{
				return this._KASAADI;
			}
			set
			{
				if ((this._KASAADI != value))
				{
					this._KASAADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIKODU", DbType="NVarChar(30)")]
		public string CARIKODU
		{
			get
			{
				return this._CARIKODU;
			}
			set
			{
				if ((this._CARIKODU != value))
				{
					this._CARIKODU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIADI", DbType="NVarChar(30)")]
		public string CARIADI
		{
			get
			{
				return this._CARIADI;
			}
			set
			{
				if ((this._CARIADI != value))
				{
					this._CARIADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGENO", DbType="NVarChar(50)")]
		public string BELGENO
		{
			get
			{
				return this._BELGENO;
			}
			set
			{
				if ((this._BELGENO != value))
				{
					this._BELGENO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this._TARIH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKTURU", DbType="NVarChar(30)")]
		public string EVRAKTURU
		{
			get
			{
				return this._EVRAKTURU;
			}
			set
			{
				if ((this._EVRAKTURU != value))
				{
					this._EVRAKTURU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKID", DbType="Int")]
		public System.Nullable<int> EVRAKID
		{
			get
			{
				return this._EVRAKID;
			}
			set
			{
				if ((this._EVRAKID != value))
				{
					this._EVRAKID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIRIS", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GIRIS
		{
			get
			{
				return this._GIRIS;
			}
			set
			{
				if ((this._GIRIS != value))
				{
					this._GIRIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIKIS", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CIKIS
		{
			get
			{
				return this._CIKIS;
			}
			set
			{
				if ((this._CIKIS != value))
				{
					this._CIKIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this._ACIKLAMA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_KASALISTESI")]
	public partial class VW_KASALISTESI
	{
		
		private int _ID;
		
		private string _KASAKODU;
		
		private string _KASAADI;
		
		private string _ACIKLAMA;
		
		private System.Nullable<decimal> _GIRIS;
		
		private System.Nullable<decimal> _CIKIS;
		
		private System.Nullable<decimal> _BAKIYE;
		
		public VW_KASALISTESI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAKODU", DbType="NVarChar(30)")]
		public string KASAKODU
		{
			get
			{
				return this._KASAKODU;
			}
			set
			{
				if ((this._KASAKODU != value))
				{
					this._KASAKODU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KASAADI", DbType="NVarChar(30)")]
		public string KASAADI
		{
			get
			{
				return this._KASAADI;
			}
			set
			{
				if ((this._KASAADI != value))
				{
					this._KASAADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this._ACIKLAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIRIS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> GIRIS
		{
			get
			{
				return this._GIRIS;
			}
			set
			{
				if ((this._GIRIS != value))
				{
					this._GIRIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIKIS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CIKIS
		{
			get
			{
				return this._CIKIS;
			}
			set
			{
				if ((this._CIKIS != value))
				{
					this._CIKIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAKIYE", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> BAKIYE
		{
			get
			{
				return this._BAKIYE;
			}
			set
			{
				if ((this._BAKIYE != value))
				{
					this._BAKIYE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_BANKAHAREKETLERI")]
	public partial class TBL_BANKAHAREKETLERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _BANKAID;
		
		private System.Nullable<int> _CARIID;
		
		private string _BELGENO;
		
		private System.Nullable<System.DateTime> _TARIH;
		
		private string _EVRAKTURU;
		
		private System.Nullable<int> _EVRAKID;
		
		private string _GCKODU;
		
		private System.Nullable<decimal> _TUTAR;
		
		private string _ACIKLAMA;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDITDATE;
		
		private System.Nullable<int> _EDITUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBANKAIDChanging(System.Nullable<int> value);
    partial void OnBANKAIDChanged();
    partial void OnCARIIDChanging(System.Nullable<int> value);
    partial void OnCARIIDChanged();
    partial void OnBELGENOChanging(string value);
    partial void OnBELGENOChanged();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    partial void OnEVRAKTURUChanging(string value);
    partial void OnEVRAKTURUChanged();
    partial void OnEVRAKIDChanging(System.Nullable<int> value);
    partial void OnEVRAKIDChanged();
    partial void OnGCKODUChanging(string value);
    partial void OnGCKODUChanged();
    partial void OnTUTARChanging(System.Nullable<decimal> value);
    partial void OnTUTARChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDITDATEChanged();
    partial void OnEDITUSERChanging(System.Nullable<int> value);
    partial void OnEDITUSERChanged();
    #endregion
		
		public TBL_BANKAHAREKETLERI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKAID", DbType="Int")]
		public System.Nullable<int> BANKAID
		{
			get
			{
				return this._BANKAID;
			}
			set
			{
				if ((this._BANKAID != value))
				{
					this.OnBANKAIDChanging(value);
					this.SendPropertyChanging();
					this._BANKAID = value;
					this.SendPropertyChanged("BANKAID");
					this.OnBANKAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIID", DbType="Int")]
		public System.Nullable<int> CARIID
		{
			get
			{
				return this._CARIID;
			}
			set
			{
				if ((this._CARIID != value))
				{
					this.OnCARIIDChanging(value);
					this.SendPropertyChanging();
					this._CARIID = value;
					this.SendPropertyChanged("CARIID");
					this.OnCARIIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGENO", DbType="NVarChar(30)")]
		public string BELGENO
		{
			get
			{
				return this._BELGENO;
			}
			set
			{
				if ((this._BELGENO != value))
				{
					this.OnBELGENOChanging(value);
					this.SendPropertyChanging();
					this._BELGENO = value;
					this.SendPropertyChanged("BELGENO");
					this.OnBELGENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKTURU", DbType="NVarChar(30)")]
		public string EVRAKTURU
		{
			get
			{
				return this._EVRAKTURU;
			}
			set
			{
				if ((this._EVRAKTURU != value))
				{
					this.OnEVRAKTURUChanging(value);
					this.SendPropertyChanging();
					this._EVRAKTURU = value;
					this.SendPropertyChanged("EVRAKTURU");
					this.OnEVRAKTURUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKID", DbType="Int")]
		public System.Nullable<int> EVRAKID
		{
			get
			{
				return this._EVRAKID;
			}
			set
			{
				if ((this._EVRAKID != value))
				{
					this.OnEVRAKIDChanging(value);
					this.SendPropertyChanging();
					this._EVRAKID = value;
					this.SendPropertyChanged("EVRAKID");
					this.OnEVRAKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCKODU", DbType="NVarChar(1)")]
		public string GCKODU
		{
			get
			{
				return this._GCKODU;
			}
			set
			{
				if ((this._GCKODU != value))
				{
					this.OnGCKODUChanging(value);
					this.SendPropertyChanging();
					this._GCKODU = value;
					this.SendPropertyChanged("GCKODU");
					this.OnGCKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUTAR", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TUTAR
		{
			get
			{
				return this._TUTAR;
			}
			set
			{
				if ((this._TUTAR != value))
				{
					this.OnTUTARChanging(value);
					this.SendPropertyChanging();
					this._TUTAR = value;
					this.SendPropertyChanged("TUTAR");
					this.OnTUTARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDITDATE
		{
			get
			{
				return this._EDITDATE;
			}
			set
			{
				if ((this._EDITDATE != value))
				{
					this.OnEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._EDITDATE = value;
					this.SendPropertyChanged("EDITDATE");
					this.OnEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITUSER", DbType="Int")]
		public System.Nullable<int> EDITUSER
		{
			get
			{
				return this._EDITUSER;
			}
			set
			{
				if ((this._EDITUSER != value))
				{
					this.OnEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._EDITUSER = value;
					this.SendPropertyChanged("EDITUSER");
					this.OnEDITUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_BANKALAR")]
	public partial class TBL_BANKALAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HESAPNO;
		
		private string _IBAN;
		
		private string _BANKAADI;
		
		private string _HESAPADI;
		
		private string _SUBE;
		
		private string _TELEFON;
		
		private string _ADRES;
		
		private string _TEMSILCI;
		
		private string _TEMSILCIEMAIL;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDITDATE;
		
		private System.Nullable<int> _EDITUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHESAPNOChanging(string value);
    partial void OnHESAPNOChanged();
    partial void OnIBANChanging(string value);
    partial void OnIBANChanged();
    partial void OnBANKAADIChanging(string value);
    partial void OnBANKAADIChanged();
    partial void OnHESAPADIChanging(string value);
    partial void OnHESAPADIChanged();
    partial void OnSUBEChanging(string value);
    partial void OnSUBEChanged();
    partial void OnTELEFONChanging(string value);
    partial void OnTELEFONChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    partial void OnTEMSILCIChanging(string value);
    partial void OnTEMSILCIChanged();
    partial void OnTEMSILCIEMAILChanging(string value);
    partial void OnTEMSILCIEMAILChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDITDATEChanged();
    partial void OnEDITUSERChanging(System.Nullable<int> value);
    partial void OnEDITUSERChanged();
    #endregion
		
		public TBL_BANKALAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPNO", DbType="NVarChar(30)")]
		public string HESAPNO
		{
			get
			{
				return this._HESAPNO;
			}
			set
			{
				if ((this._HESAPNO != value))
				{
					this.OnHESAPNOChanging(value);
					this.SendPropertyChanging();
					this._HESAPNO = value;
					this.SendPropertyChanged("HESAPNO");
					this.OnHESAPNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAN", DbType="NVarChar(50)")]
		public string IBAN
		{
			get
			{
				return this._IBAN;
			}
			set
			{
				if ((this._IBAN != value))
				{
					this.OnIBANChanging(value);
					this.SendPropertyChanging();
					this._IBAN = value;
					this.SendPropertyChanged("IBAN");
					this.OnIBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKAADI", DbType="NVarChar(30)")]
		public string BANKAADI
		{
			get
			{
				return this._BANKAADI;
			}
			set
			{
				if ((this._BANKAADI != value))
				{
					this.OnBANKAADIChanging(value);
					this.SendPropertyChanging();
					this._BANKAADI = value;
					this.SendPropertyChanged("BANKAADI");
					this.OnBANKAADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPADI", DbType="NVarChar(30)")]
		public string HESAPADI
		{
			get
			{
				return this._HESAPADI;
			}
			set
			{
				if ((this._HESAPADI != value))
				{
					this.OnHESAPADIChanging(value);
					this.SendPropertyChanging();
					this._HESAPADI = value;
					this.SendPropertyChanged("HESAPADI");
					this.OnHESAPADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBE", DbType="NVarChar(30)")]
		public string SUBE
		{
			get
			{
				return this._SUBE;
			}
			set
			{
				if ((this._SUBE != value))
				{
					this.OnSUBEChanging(value);
					this.SendPropertyChanging();
					this._SUBE = value;
					this.SendPropertyChanged("SUBE");
					this.OnSUBEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON", DbType="NVarChar(16)")]
		public string TELEFON
		{
			get
			{
				return this._TELEFON;
			}
			set
			{
				if ((this._TELEFON != value))
				{
					this.OnTELEFONChanging(value);
					this.SendPropertyChanging();
					this._TELEFON = value;
					this.SendPropertyChanged("TELEFON");
					this.OnTELEFONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMSILCI", DbType="NVarChar(50)")]
		public string TEMSILCI
		{
			get
			{
				return this._TEMSILCI;
			}
			set
			{
				if ((this._TEMSILCI != value))
				{
					this.OnTEMSILCIChanging(value);
					this.SendPropertyChanging();
					this._TEMSILCI = value;
					this.SendPropertyChanged("TEMSILCI");
					this.OnTEMSILCIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEMSILCIEMAIL", DbType="NVarChar(150)")]
		public string TEMSILCIEMAIL
		{
			get
			{
				return this._TEMSILCIEMAIL;
			}
			set
			{
				if ((this._TEMSILCIEMAIL != value))
				{
					this.OnTEMSILCIEMAILChanging(value);
					this.SendPropertyChanging();
					this._TEMSILCIEMAIL = value;
					this.SendPropertyChanged("TEMSILCIEMAIL");
					this.OnTEMSILCIEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDITDATE
		{
			get
			{
				return this._EDITDATE;
			}
			set
			{
				if ((this._EDITDATE != value))
				{
					this.OnEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._EDITDATE = value;
					this.SendPropertyChanged("EDITDATE");
					this.OnEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITUSER", DbType="Int")]
		public System.Nullable<int> EDITUSER
		{
			get
			{
				return this._EDITUSER;
			}
			set
			{
				if ((this._EDITUSER != value))
				{
					this.OnEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._EDITUSER = value;
					this.SendPropertyChanged("EDITUSER");
					this.OnEDITUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_BANKADURUM")]
	public partial class VW_BANKADURUM
	{
		
		private int _ID;
		
		private System.Nullable<decimal> _GIRIS;
		
		private System.Nullable<decimal> _CIKIS;
		
		private System.Nullable<decimal> _BAKIYE;
		
		public VW_BANKADURUM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIRIS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> GIRIS
		{
			get
			{
				return this._GIRIS;
			}
			set
			{
				if ((this._GIRIS != value))
				{
					this._GIRIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIKIS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CIKIS
		{
			get
			{
				return this._CIKIS;
			}
			set
			{
				if ((this._CIKIS != value))
				{
					this._CIKIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAKIYE", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> BAKIYE
		{
			get
			{
				return this._BAKIYE;
			}
			set
			{
				if ((this._BAKIYE != value))
				{
					this._BAKIYE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_BANKAHAREKETLERI")]
	public partial class VW_BANKAHAREKETLERI
	{
		
		private int _ID;
		
		private System.Nullable<int> _BANKAID;
		
		private System.Nullable<int> _CARIID;
		
		private string _BELGENO;
		
		private System.Nullable<System.DateTime> _TARIH;
		
		private string _EVRAKTURU;
		
		private System.Nullable<int> _EVRAKID;
		
		private System.Nullable<decimal> _TUTAR;
		
		private string _ACIKLAMA;
		
		private System.Nullable<decimal> _GIRIS;
		
		private System.Nullable<decimal> _CIKIS;
		
		private string _HESAPADI;
		
		private string _HESAPNO;
		
		public VW_BANKAHAREKETLERI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKAID", DbType="Int")]
		public System.Nullable<int> BANKAID
		{
			get
			{
				return this._BANKAID;
			}
			set
			{
				if ((this._BANKAID != value))
				{
					this._BANKAID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIID", DbType="Int")]
		public System.Nullable<int> CARIID
		{
			get
			{
				return this._CARIID;
			}
			set
			{
				if ((this._CARIID != value))
				{
					this._CARIID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGENO", DbType="NVarChar(30)")]
		public string BELGENO
		{
			get
			{
				return this._BELGENO;
			}
			set
			{
				if ((this._BELGENO != value))
				{
					this._BELGENO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this._TARIH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKTURU", DbType="NVarChar(30)")]
		public string EVRAKTURU
		{
			get
			{
				return this._EVRAKTURU;
			}
			set
			{
				if ((this._EVRAKTURU != value))
				{
					this._EVRAKTURU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVRAKID", DbType="Int")]
		public System.Nullable<int> EVRAKID
		{
			get
			{
				return this._EVRAKID;
			}
			set
			{
				if ((this._EVRAKID != value))
				{
					this._EVRAKID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUTAR", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TUTAR
		{
			get
			{
				return this._TUTAR;
			}
			set
			{
				if ((this._TUTAR != value))
				{
					this._TUTAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this._ACIKLAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIRIS", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GIRIS
		{
			get
			{
				return this._GIRIS;
			}
			set
			{
				if ((this._GIRIS != value))
				{
					this._GIRIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIKIS", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CIKIS
		{
			get
			{
				return this._CIKIS;
			}
			set
			{
				if ((this._CIKIS != value))
				{
					this._CIKIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPADI", DbType="NVarChar(30)")]
		public string HESAPADI
		{
			get
			{
				return this._HESAPADI;
			}
			set
			{
				if ((this._HESAPADI != value))
				{
					this._HESAPADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPNO", DbType="NVarChar(30)")]
		public string HESAPNO
		{
			get
			{
				return this._HESAPNO;
			}
			set
			{
				if ((this._HESAPNO != value))
				{
					this._HESAPNO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_BANKALISTESI")]
	public partial class VW_BANKALISTESI
	{
		
		private int _ID;
		
		private string _HESAPNO;
		
		private string _IBAN;
		
		private string _BANKAADI;
		
		private System.Nullable<decimal> _GIRIS;
		
		private System.Nullable<decimal> _CIKIS;
		
		private System.Nullable<decimal> _BAKIYE;
		
		private string _HESAPADI;
		
		public VW_BANKALISTESI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPNO", DbType="NVarChar(30)")]
		public string HESAPNO
		{
			get
			{
				return this._HESAPNO;
			}
			set
			{
				if ((this._HESAPNO != value))
				{
					this._HESAPNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAN", DbType="NVarChar(50)")]
		public string IBAN
		{
			get
			{
				return this._IBAN;
			}
			set
			{
				if ((this._IBAN != value))
				{
					this._IBAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKAADI", DbType="NVarChar(30)")]
		public string BANKAADI
		{
			get
			{
				return this._BANKAADI;
			}
			set
			{
				if ((this._BANKAADI != value))
				{
					this._BANKAADI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIRIS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> GIRIS
		{
			get
			{
				return this._GIRIS;
			}
			set
			{
				if ((this._GIRIS != value))
				{
					this._GIRIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIKIS", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CIKIS
		{
			get
			{
				return this._CIKIS;
			}
			set
			{
				if ((this._CIKIS != value))
				{
					this._CIKIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAKIYE", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> BAKIYE
		{
			get
			{
				return this._BAKIYE;
			}
			set
			{
				if ((this._BAKIYE != value))
				{
					this._BAKIYE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPADI", DbType="NVarChar(30)")]
		public string HESAPADI
		{
			get
			{
				return this._HESAPADI;
			}
			set
			{
				if ((this._HESAPADI != value))
				{
					this._HESAPADI = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
